// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ALink: typeof import('./src/components/ALink/index.vue')['default']
    BankCardInfo: typeof import('./src/components/merchant/bankCardInfo.vue')['default']
    BasicInfo: typeof import('./src/components/merchant/basicInfo.vue')['default']
    BreadCrumbs: typeof import('./src/components/BreadCrumbs/index.vue')['default']
    Error: typeof import('./src/components/Result/svg/error.vue')['default']
    IconSvg: typeof import('./src/components/IconSvg/index.vue')['default']
    IdCardInfo: typeof import('./src/components/merchant/idCardInfo.vue')['default']
    Info: typeof import('./src/components/Result/svg/info.vue')['default']
    NoFound: typeof import('./src/components/Result/svg/noFound.vue')['default']
    Permission: typeof import('./src/components/Permission/index.vue')['default']
    Result: typeof import('./src/components/Result/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerError: typeof import('./src/components/Result/svg/serverError.vue')['default']
    Spin: typeof import('./src/components/Spin/index.vue')['default']
    Success: typeof import('./src/components/Result/svg/success.vue')['default']
    Unauthorized: typeof import('./src/components/Result/svg/unauthorized.vue')['default']
    UploadImg: typeof import('./src/components/common/uploadImg.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanUploader: typeof import('vant/es')['Uploader']
    Warning: typeof import('./src/components/Result/svg/warning.vue')['default']
  }
}

export {}
