export default [
  {
    name: "班级管理",
    color: "#FFB73B",
    icon: "bjgl",
    show: true,
    title: "校务管理",
    path: "班级管理",
  },
  {
    name: "幼儿管理",
    color: "#46A7FF",
    icon: "yrgl",
    show: true,
    title: "校务管理",
    path: "幼儿管理",
  },
  {
    name: "家长管理",
    color: "#46A7FF",
    icon: "jzgl",
    show: false,
    title: "校务管理",
    path: "家长管理",
  },
  {
    name: "教职工管理",
    color: "#A49BE2",
    icon: "jzggl",
    show: true,
    title: "校务管理",
    path: "教职工管理",
  },
  {
    name: "考勤管理",
    color: "#46A7FF",
    icon: "kqgl",
    show: true,
    title: "校务管理",
    path: "幼儿考勤",
  },
  {
    name: "园所收费",
    color: "#3DC2C1",
    icon: "yssf",
    show: true,
    title: "校务管理",
    path: "园所收费",
  },
  {
    name: "监控视频",
    color: "#46A7FF",
    icon: "jksp",
    show: true,
    title: "校务管理",
    path: "视频管理",
  },
  {
    name: "招生宣传",
    color: "#FE6F6F",
    icon: "zsxc",
    show: true,
    title: "校务管理",
    path: "校园手机官网",
  },
  {
    name: "报名幼儿",
    color: "#FFB73B",
    icon: "bmyr",
    show: false,
    title: "校务管理",
    path: "报名幼儿管理",
  },
  {
    name: "学籍信息",
    color: "#3DC2C1",
    icon: "xjxx",
    show: true,
    title: "校务管理",
    path: "学籍信息",
  },
  {
    name: "评论管理",
    color: "#3DC2C1",
    icon: "plgl",
    show: true,
    title: "校务管理",
    path: "评论管理",
  },
  {
    name: "数据中心",
    color: "#46A7FF",
    icon: "sjzx",
    show: true,
    title: "校务管理",
    path: "数据中心",
  },
  {
    name: "系统设置",
    color: "#46A7FF",
    icon: "xtsz",
    show: true,
    title: "校务管理",
    path: "系统设置",
  },
  {
    name: "账号设置",
    color: "#46A7FF",
    icon: "zhsz",
    show: false,
    title: "校务管理",
    path: "",
  },
  {
    name: "操作日志",
    color: "#46A7FF",
    icon: "czrz",
    show: false,
    title: "校务管理",
    path: "系统设置",
  },
  {
    name: "发通知",
    color: "#46A7FF",
    icon: "ftz",
    show: true,
    title: "信息发布",
    path: "发布通知",
  },
  {
    name: "发动态",
    color: "#3DC2C1",
    icon: "fdt",
    show: true,
    title: "信息发布",
    path: "",
  },
  {
    name: "发食谱",
    color: "#FFB73B",
    icon: "fsp",
    show: true,
    title: "信息发布",
    path: "通知",
  },
  {
    name: "发直播",
    color: "#FE6F6F",
    icon: "fzb",
    show: true,
    title: "信息发布",
    path: "发布直播",
  },
  {
    name: "选课中心",
    color: "#46A7FF",
    icon: "xkzx",
    show: true,
    title: "教学备课",
    path: "选课中心",
  },
  {
    name: "招生课程",
    color: "#46A7FF",
    icon: "zskc",
    show: false,
    title: "教学备课",
    path: "",
  },
  {
    name: "课表",
    color: "#3DC2C1",
    icon: "kb",
    show: false,
    title: "教学备课",
    path: "",
  },
];
